# NUKE CLI Configuration

targets:
  - node_modules
  - .next
  - .nuxt
  - dist
  - .cache
  - target
  - __pycache__
  - .venv
  - venv
  - .parcel-cache
  - coverage
  - .nyc_output

ignore:
  - build
  - bin
  - obj
  - .git
  - .svn
  - .hg
  - .vscode
  - .idea
  - System32
  - Windows
  - Program Files
  - Program Files (x86)

settings:
  strategy: os-fast
  scan_threads: 8
