# NUKE CLI Configuration

targets:
  - node_modules
  - .next
  - .nuxt
  - dist
  - .cache
  - target
  - __pycache__
  - .venv
  - venv
  - .parcel-cache
  - .turbo
  - coverage
  - .nyc_output

ignore:
  - build
  - bin
  - obj
  - .git
  - .svn
  - .hg
  - .vscode
  - .idea
  - System32
  - Windows
  - Program Files
  - Program Files (x86)

# Cài đặt
settings:
  # Chiến lược xóa: "os-fast" (dùng robocopy) hoặc "native" (dùng filesystem API)
  strategy: os-fast
  # Số luồng quét song song
  scan_threads: 8
